### ISSUE TITLE
i’m noob!need some install help:(

### ISSUE THREAD

**Issue by chinalhx** [berarma/new-lg4ff#100]
I am a newbie in arch linux. Following your method, I successfully installed oversteer+ Thrustmaster T300 RS with hid-tmff2
However, now a new question comes, how do I install new-lg 4ff?
 Is there any one-click installation command suitable for Arch Linux novices? I am willing to buy a cup of coffee as a sponsor@berarma

**Comment by chinalhx** [comment]
To be honest, I feel disgusted when I see various commands now, especially when I need to spend time to find a solution
So is there anything I can install with one click? Or copy what you wrote so that it can be used on steamos (archlinux system)? This will make it easier for me to install new-lg4ff

**Comment by berarma** [comment]
> To be honest, I feel disgusted when I see various commands now, especially when I need to spend time to find a solution
> So is there anything I can install with one click? Or copy what you wrote so that it can be used on steamos (archlinux system)? This will make it easier for me to install new-lg4ff

Do you have a Logitech wheel?

**Comment by chinalhx** [comment]
> > To be honest, I feel disgusted when I see various commands now, especially when I need to spend time to find a solution
> > So is there anything I can install with one click? Or copy what you wrote so that it can be used on steamos (archlinux system)? This will make it easier for me to install new-lg4ff
> 
> Do you have a Logitech wheel?

yep！my devices:Steamdeck oiled+Logitech G29(include H shift), Just after this post was posted, I tried to install it myself. I don’t know if it was successful. When I used the’ sudo dmegs ‘command, the output showed loading out of tree.
here’s output link: https://github.com/berarma/new-lg4ff/issues/101

**Comment by berarma** [comment]
Answering the original question, there's no one-click command but instructions should be enough.
