### ISSUE TITLE
Version 0.2 not working

### ISSUE THREAD

**Issue by writequit** [berarma/new-lg4ff#19]
Hi Bernat,

Firstly thanks for taking the trouble to create a working driver for us,  I've got a G29 and have been using version 0.1 in pcars2, ATS and Mudrunner and it's been working well. 

I updated to version 0.2 a short while ago using dkms, rebooted and connected the wheel and get an oops https://pastebin.com/aY4y5n31

Reverted to 0.1 and working again.

Regards,
Geoff

**Comment by berarma** [comment]
This is the same as #20. Something is causing the wheel to disconnect and it triggers an error.

Thanks for reporting.

**Comment by berarma** [comment]
It's fixed in the master branch, please test it and confirm it works.

**Comment by writequit** [comment]
I confirm it's working without issue now, loaded the new module, no oops, couple of laps around the Nordschleife, all good :)

Thank you!

**Comment by berarma** [comment]
Thanks for reporting.
