### ISSUE TITLE
Any extra steps to make G29 work?

### ISSUE THREAD

**Issue by GreatBigWhiteWorld** [berarma/new-lg4ff#22]
Hello, thank you for the great project!
I've just got my G29 wheel only yesterday and I'm trying to get it to work today on a opensuse machine.
So far Dirt rally works out of the box.
But on Dirt rally 2.0 I can't have FFB to work (0 feedback).
I've installed the mod following the tutorial and it all went through and I can see the mod is loaded.
However I still don't get no ffb in the game at all.
My questions are:
1.What proton versions are recommended? So far 4.11 and 4.2 did not work.
2.And do I need to add some launch options for the game? 
3.BTW I found pyLinuxwheel to set up the wheel and no problem there, since when I launch it I can see that at least centering spring is working. Should I switch to oversteer to get this to work?
4.Do I need ffbtools to get this to work.
Sorry for the newbie questions!

**Comment by berarma** [comment]
DR2 needs Proton 4.11-12 and ffbtools. Please, see the launch options example in https://github.com/ValveSoftware/Proton/issues/2366#issuecomment-544434688. Adjust the paths to your system.

Once it's working you can try new-lg4ff. It will add some missing FFB effects.

I'm glad to help but Proton game issues should go to the Proton tracker.
