### ISSUE TITLE
Module causing system instability

### ISSUE THREAD

**Issue by 3rikk** [berarma/new-lg4ff#31]
having this module installed (using dkms) caused system instability like random crashes and random softlock at bootup.
Using Pop!_OS, no other dkms modules (apart from preinstalled ones) on a Ryzen 5 1600
Edit: need to do a bit more testing, just incase this is caused by something else

**Comment by berarma** [comment]
Please, confirm that the crashes only happen when loading this module. Many people has been using the module for some time and there hasn't been any instability reported before.

Try it with the wheel device disconnected too and see if there's any difference. Report your device model, kernel version, dmesg and syslog files.
