### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sticsk** [berarma/new-lg4ff#32]
Sorry if it's not an issue or recommandation, but I really want to thank you very much, beacuse now I can really enjoy Linux thanks to this and Oversteer.

I tested it on my Manjaro laptop and PC and they both run this very well, using it with linux57 kernel.

**Comment by berarma** [comment]
You're welcomed. It's always nice reading success stories.

May I ask which wheel device do you use?

Thanks!

**Comment by sticsk** [comment]
I'm using Logitech G29, now since I'm on PS4 I usually play Dirt Rally 2 there.

But I still enjoy ETS2, I'm playing it right now and I've been searching for a year for making ffb to work, thank you very much

**Comment by berarma** [comment]
Following the projects, testing the latest releases and reporting any issues would be very helpful.

Anyway, I'm glad you're enjoying it.
