### ISSUE TITLE
Old kernel compilation fixes

### ISSUE THREAD

**Issue by madbad** [berarma/new-lg4ff#33]
I friend that does not have a github account asked me to submit this patch that allow the driver to be compiled on older kernels
[logitech-ff-20200922.txt](https://github.com/berarma/new-lg4ff/files/5257857/logitech-ff-20200922.txt)

**Comment by berarma** [comment]
Next release will most probably remove the lowres timer since I think no one needs it. That means this patch would be removed too and wouldn't get to be released. I think I'll wait unless there's more people with this issue. I didn't expect anyone using kernels this old.

**Comment by berarma** [comment]
I've removed the lowres timer so this shouldn't be a problem anymore.
