### ISSUE TITLE
Further Explanation and Uninstalling?

### ISSUE THREAD

**Issue by b-zhang93** [berarma/new-lg4ff#39]
This looks super interesting, but I am having some trouble understanding the full effects of this module. 

Could you explain how this will improve my G27 wheel which is working on my windows 10 computer with Logitech profiler?

Also if I wish to uninstall in the future, how would I go about this?

Thanks!

**Comment by berarma** [comment]
This won't work on any Windows system, and you don't need it either. It's a driver for Linux systems only. I'll make it more clear in the description and docs.
