### ISSUE TITLE
Force feedback command queue

### ISSUE THREAD

**Issue by davidjmemmett** [berarma/new-lg4ff#40]
I'm able to reproduce an issue consistently whereby the force feedback command queue builds up into the thousands.

Whilst playing Assetto Corsa (via Proton Experimental), during the start of a race whilst the cars are sat on the grid, the "Force feedback command queue contains _x_ commands, causing substantial delays!" kernel message is written several times a second, sometimes incrementing by one or two hundred. Whilst sat on the grid, I can feel the feedback through the wheel, however the number continues to climb. It is only after the race begins that the number starts to decrease - whereby for the first lap the wheel goes a bit insane trying to catch up (assuming it's emptying the queue as the number is going down).

Using latest new-lg4ff (commit e7a3b2408ee60fff8bb0c8563ee57a266d55d9cf) with Logitech G920 (apparently the same if not very similar to the G29).

I'm wondering if it might be worth having an upper limit on the number of items in the queue, as realistically any commands sent in the past which weren't executed immediately are useless, negatively affecting the game experience.

**Comment by berarma** [comment]
This module does nothing for the G920. Please, read the README. You're using the module in the kernel for HID++ devices.

My other project ffbtools has a workaround for this issue.
