### ISSUE TITLE
Solved F1 2018 FFB problem

### ISSUE THREAD

**Issue by Norodix** [berarma/new-lg4ff#41]
With F1 2018 I had the problem that the game would apply a constant force to the wheel and keep it there even during cutscenes, in the menu or after closing the game. I was afraid that it could burn the motor inside the wheel, so I had to use some workarounds.
This module solved this problem.
If someone else has similar problems you should try installing this module.
Wheel is G25, the problem was present both in Ubuntu 20.04 and PopOS 20.10.

Thank you!

**Comment by berarma** [comment]
Thanks for the positive report.
