### ISSUE TITLE
PS3 vs PS4 mode for Logitech G29?

### ISSUE THREAD

**Issue by Espionage724** [berarma/new-lg4ff#53]
I've noticed that when using my G29 on Linux, the PS4 mode doesn't seem to present any force-feedback option. But in PS3 mode, it presents force-feedback with both the stock driver and this module.

1. Are there any technical reasons why the PS4 mode doesn't seemingly work in Linux? It's the preferred mode for Windows.
2. Can this driver be modified to work with the PS4 mode?
3. What are the actual differences between the PS3 and PS4 mode? I believe on the surface, the RPM meter on the wheel doesn't work on PS3 mode, but on a technical level, I'm interested to know why this is, and other differences

**Comment by berarma** [comment]
> I've noticed that when using my G29 on Linux, the PS4 mode doesn't seem to present any force-feedback option. But in PS3 mode, it presents force-feedback with both the stock driver and this module.
> 
> 1. Are there any technical reasons why the PS4 mode doesn't seemingly work in Linux? It's the preferred mode for Windows.

That mode isn't implemented. Logitech released information only for the PS3 mode.

> 2. Can this driver be modified to work with the PS4 mode?

I don't know how much work would be needed.

> 3. What are the actual differences between the PS3 and PS4 mode? I believe on the surface, the RPM meter on the wheel doesn't work on PS3 mode, but on a technical level, I'm interested to know why this is, and other differences

Everything works in PS3 mode, including the RPM leds. There's no reason to prefer the PS4 mode as far as I know.
