### ISSUE TITLE
Project CARS 3 has no FFB or resistance

### ISSUE THREAD

**Issue by Espionage724** [berarma/new-lg4ff#54]
[Project CARS 3](https://store.steampowered.com/app/958400) when ran through Proton Experimental and this driver has no FFB nor resistance on the wheel. It seems fine from the default kernel module though.

Any suggestions I could do to try to debug this?

I'm not sure if the same suggestion for an older Proton build here works https://github.com/berarma/new-lg4ff/issues/30#issuecomment-644224921, but I'll try that in a bit

**Comment by berarma** [comment]
I use only official Proton versions, other versions might not work and it's probably not related to the driver. Please, make sure the driver is working with at least some games and let's see which ones.

PC3, does it work with last Proton stable version?

Please, check for errors and make sure the driver is properly loaded looking in dmesg output.
