### ISSUE TITLE
Add range to sysfs

### ISSUE THREAD

**Issue by kozr** [berarma/new-lg4ff#56]
Is there a reason it isn't added yet? I'd love to be able to control rc cars via sysfs.

**Comment by berarma** [comment]
There's already a range entry to control the rotation range of the wheel. Can you give more details?

**Comment by kozr** [comment]
https://github.com/berarma/new-lg4ff/blob/32c45a2eefc4b185f4fa1eeff9a264271a005441/hid-lg4ff.c#L2227 I see, nevermind. It was just missed in the readme.md

**Comment by berarma** [comment]
The README lists only new settings added by this driver.
