### ISSUE TITLE
Freshly introduced compilation error by typo in hid-lg4ff.c:708

### ISSUE THREAD

**Issue by DilithiumNitrate** [berarma/new-lg4ff#70]
Not much to say here. This line:
```c
parameters->clip = (unsigned)condition->right_saturation);
```
shouldn't have that trailing parenthesis left over from what the line looked before the last commit. Removing it lets this driver compile properly. Do you not test this driver before pushing commits?

**Comment by berarma** [comment]
I usually do but something happened with this commit.
