### ISSUE TITLE
LinuxMint DKMS Module not Loading

### ISSUE THREAD

**Issue by izzijaz** [berarma/new-lg4ff#74]
I followed the DKMS installation instructions. and updated initramfs and rebooted. when i run dmesg no module related to logitech even comes up.  Playing games make the force feedback vibrate loud even when the car is stopped.

**Comment by izzijaz** [comment]
Somehow popped up when i plugged the controller into the PC. Im guessing the module only gets loaded if the device is connected.

**Comment by izzijaz** [comment]
Logitech G29, i just connected the controller and tried, now it shows. Even after i disconnect the WHeel its still loaded. Im guesing everything working the way i should now.

**Comment by berarma** [comment]
> Somehow popped up when i plugged the controller into the PC. Im guessing the module only gets loaded if the device is connected.

That's how modules work, they're loaded when needed. You must do all checks above with the wheel connected.

Does it work correctly now?

**Comment by izzijaz** [comment]
Yesterday while playing we noticed really bad FFB from the wheel. COntroller was vibrating even at idle speeds. vibration was very loud also. I dont think the driver was properly loaded yesterday. Could not use the 3 FFB settings in oversteer also. Im hoping now the issue is ok.

**Comment by izzijaz** [comment]
I may have glitched everything by installing using DKMS and then using make load to load the module. Now i removed the files manually and installed again.

**Comment by izzijaz** [comment]
The wheel is wobbling on NFSMW. It doesn't start that eay but half way into the race, the wheel starts behaving like that and then even aftee restarting race it keeps wobbling. This didn't happen the first day we played this game.

**Comment by berarma** [comment]
Well, the initial issue in the title is fixed. You should create a new issue so this doesn't get buried.

Although maybe you would get more help in the [corresponding Proton issue](https://github.com/ValveSoftware/Proton/issues/4510) in case you're using Proton.

If you still want me to take a look, please, open a new issue and attach a log created with [ffbtools](https://github.com/berarma/ffbtools/blob/master/docs/ffbwrap.md).
