### ISSUE TITLE
Uninstalled, but the previous drivers did not load?

### ISSUE THREAD

**Issue by doordormeta** [berarma/new-lg4ff#75]
Hi,

With original driver the steering and pedals did not work for me, but force feedback did.

I installed new-lg4ff, the steering and pedals worked but the force feedback didn't.

I uninstalled and removed the dkms module but the original driver/force feedback does not work.

How can I uninstall this to the point where the force feedback works again?

**Comment by berarma** [comment]
Can I ask you which wheel do you have?
