### ISSUE TITLE
[question] steering control?

### ISSUE THREAD

**Issue by CarlDegio** [berarma/new-lg4ff#79]
In the game of Horizon 5, I found that the steering wheel sometimes turned itself due to the terrain.

I want to reproduce this behavior using the code for autodrive by G923 (make the steering wheel follow the front wheels of the car). But I found that the SDK provided here seems to only make the steering wheel return to the center with different stiffnesses.

Is there some API that can directly control the angle of the steering wheel or apply torque?

**Comment by CarlDegio** [comment]
https://github.com/nightmode/logitech-g29/issues/2 would be a reference method

**Comment by berarma** [comment]
If I've understood correctly, you could use a FF_SPRING effect with the center parameter set where you want it.

**Comment by CarlDegio** [comment]
Thank you! This might be helpful. At the same time, I would like to ask how to adjust the FF? I saw in the project introduction to modify the files in `/sys/bus/hid/drivers/logitech/XXXX:XXXX:XXXX.XXXX/` to adjust the behavior. I don't quite understand how to adjust FF_SPRING
