### ISSUE TITLE
Kernel Version Outdates

### ISSUE THREAD

**Issue by p3e** [berarma/new-lg4ff#88]
Current source is 11.3.0 rather than 11.4.0
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  You are using:           gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by berarma** [comment]
I don't get to decide which kernel and compiler you run. Use the kernel and compiler distributed with your distro.
