### ISSUE TITLE
System message complains about kernel being tainted

### ISSUE THREAD

**Issue by oldlinuxenthusiast** [berarma/new-lg4ff#9]
Hey - Thanks for putting the time into improving the FF experience for linux sim racers. When I installed, there is a message in dmesg complaining that the kernel is tainted. Details are below.

OS: Xubuntu 19.10
Kernel: 5.3.0-23-generic
dmesg:
`[48323.780734] hid_logitech_new: loading out-of-tree module taints kernel.
[48323.780763] hid_logitech_new: module verification failed: signature and/or required key missing - tainting kernel
`

**Comment by berarma** [comment]
This is normal. Your kernel becomes tainted because the module is not in the kernel sources. See https://unix.stackexchange.com/a/116976

Most of us don't see this message because the kernel is already tainted since we load the nvidia propietary module or some other 3rd party module at boot time.
